/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.util.List;
import Entidades.Curso;
import Entidades.Profesor;
import Entidades.Estudiante;
import javax.swing.JOptionPane;
public class FrameEditarCurso extends javax.swing.JFrame {

    private List<Curso> cursos;
    public FrameEditarCurso(List<Curso> cursos) {
        initComponents();
        this.cursos= cursos;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jprincipalEditar = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JLabel();
        jPanelCodigoC = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelNombreC1 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelCreditosC = new javax.swing.JPanel();
        txtCredito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("Gestor de Cursos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jprincipalEditar.setBackground(new java.awt.Color(255, 255, 255));

        titulo2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        titulo2.setText("Curso");

        BtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(170, 26, 26));
        BtnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseExited(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(23, 194, 154));
        BtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuardar.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseExited(evt);
            }
        });

        jPanelCodigoC.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCodigoC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setBorder(null);
        jPanelCodigoC.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 260, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelCodigoC.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jPanelNombreC1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNombreC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setBorder(null);
        jPanelNombreC1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelNombreC1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jPanelCreditosC.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCreditosC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCredito.setBorder(null);
        jPanelCreditosC.add(txtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelCreditosC.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        lblCredito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCredito.setText("Credito:");

        lblcodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcodigo.setText("Codigo:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        javax.swing.GroupLayout jprincipalEditarLayout = new javax.swing.GroupLayout(jprincipalEditar);
        jprincipalEditar.setLayout(jprincipalEditarLayout);
        jprincipalEditarLayout.setHorizontalGroup(
            jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprincipalEditarLayout.createSequentialGroup()
                .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jprincipalEditarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(BtnGuardar)
                        .addGap(46, 46, 46)
                        .addComponent(BtnCancelar))
                    .addGroup(jprincipalEditarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblcodigo))
                    .addGroup(jprincipalEditarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCredito))
                    .addGroup(jprincipalEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombre))
                    .addGroup(jprincipalEditarLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(titulo2)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jprincipalEditarLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jPanelCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalEditarLayout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(jPanelNombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalEditarLayout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(jPanelCreditosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jprincipalEditarLayout.setVerticalGroup(
            jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprincipalEditarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(titulo2)
                .addGap(18, 18, 18)
                .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnGuardar))
                .addGap(31, 31, 31))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jprincipalEditarLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jPanelCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalEditarLayout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(jPanelNombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
            .addGroup(jprincipalEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprincipalEditarLayout.createSequentialGroup()
                    .addContainerGap(142, Short.MAX_VALUE)
                    .addComponent(jPanelCreditosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jprincipalEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jprincipalEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
       String codigo = txtCodigo.getText();
       String nombre = txtnombre.getText();
       String credito = txtCredito.getText();
        if(!codigo.isEmpty()&&!credito.isEmpty()&&!nombre.isEmpty()){        
            Curso cursoAgregar = new Curso(codigo, nombre,Integer.valueOf(credito));
            cursos.add(cursoAgregar);
            JOptionPane.showMessageDialog(null, "Curso Agregado",
                "Agregar", JOptionPane.INFORMATION_MESSAGE);   
        }else{
            JOptionPane.showMessageDialog(null, "Completa todos los campos",
            "Error", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseEntered
      BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuardarcambio.png")));
      BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnGuardarMouseEntered

    private void BtnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseExited
      BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuardar.png")));
      BtnGuardar.setForeground(new java.awt.Color(23, 194, 154));
    }//GEN-LAST:event_BtnGuardarMouseExited

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
       this.dispose();
        FrameGestordeCursos pantaGesto =new FrameGestordeCursos(cursos);
        pantaGesto.setVisible(true);
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseEntered
      BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCancelarcambio.png")));
      BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnCancelarMouseEntered

    private void BtnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseExited
      BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCancelar.png")));
      BtnCancelar.setForeground(new java.awt.Color(170, 26, 26));
    }//GEN-LAST:event_BtnCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCancelar;
    private javax.swing.JLabel BtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCodigoC;
    private javax.swing.JPanel jPanelCreditosC;
    private javax.swing.JPanel jPanelNombreC1;
    private javax.swing.JPanel jprincipalEditar;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel titulo2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
