/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Entidades.Curso;
import Entidades.Profesor;
import javax.swing.JOptionPane;

public class FrameEditarProfesores extends javax.swing.JFrame {
    private Curso curso;
    public FrameEditarProfesores(Curso curso) {
        initComponents();
        this.curso= curso;
        this.setLocationRelativeTo(null);
    }
    public void guardar(Profesor profesor ){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JLabel();
        jPanelCodigoC = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelNombreC1 = new javax.swing.JPanel();
        txt_credito = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelCreditosC = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BtnCancelar1 = new javax.swing.JLabel();
        BtnGuardar1 = new javax.swing.JLabel();
        jPanelNombreC2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("Curso");

        BtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(170, 26, 26));
        BtnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(23, 194, 154));
        BtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuardar.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
        });

        jPanelCodigoC.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCodigoC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_codigo.setBorder(null);
        jPanelCodigoC.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 260, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelCodigoC.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jPanelNombreC1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNombreC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_credito.setBorder(null);
        jPanelNombreC1.add(txt_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelNombreC1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        jPanelCreditosC.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCreditosC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setBorder(null);
        jPanelCreditosC.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelCreditosC.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(BtnGuardar)
                        .addGap(41, 41, 41)
                        .addComponent(BtnCancelar)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanelCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jPanelNombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(jPanelCreditosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnGuardar))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jPanelCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jPanelNombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(142, Short.MAX_VALUE)
                    .addComponent(jPanelCreditosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("Agregar Profesor");

        BtnCancelar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnCancelar1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnCancelar1.setForeground(new java.awt.Color(170, 26, 26));
        BtnCancelar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCancelar.png"))); // NOI18N
        BtnCancelar1.setText("Cancelar");
        BtnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelar1MouseClicked(evt);
            }
        });

        BtnGuardar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardar1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnGuardar1.setForeground(new java.awt.Color(23, 194, 154));
        BtnGuardar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuardar.png"))); // NOI18N
        BtnGuardar1.setText("Guardar");
        BtnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGuardar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGuardar1MouseExited(evt);
            }
        });

        jPanelNombreC2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNombreC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setBorder(null);
        jPanelNombreC2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelNombreC2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnGuardar1)
                                .addGap(40, 40, 40)
                                .addComponent(BtnCancelar1))
                            .addComponent(jPanelNombreC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNombreC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar1)
                    .addComponent(BtnCancelar1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
       Profesor profe = new Profesor();
        if(!txtnombre.getText().isEmpty()){
            profe.setNombre(txtnombre.getText());
            curso.agregarProfesor(profe);
            txtnombre.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Complete el campo nombre",
                    "Agregar", JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardar1MouseClicked
      
    }//GEN-LAST:event_BtnGuardar1MouseClicked

    private void BtnGuardar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardar1MouseEntered

    private void BtnGuardar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardar1MouseExited

    private void BtnCancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelar1MouseClicked
        this.dispose();
        FrameProfesores pantprofe = new FrameProfesores(curso);
        pantprofe.setVisible(true);
    }//GEN-LAST:event_BtnCancelar1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCancelar;
    private javax.swing.JLabel BtnCancelar1;
    private javax.swing.JLabel BtnGuardar;
    private javax.swing.JLabel BtnGuardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCodigoC;
    private javax.swing.JPanel jPanelCreditosC;
    private javax.swing.JPanel jPanelNombreC1;
    private javax.swing.JPanel jPanelNombreC2;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_credito;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
