/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;
import Entidades.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class FrameGestordeCursos extends javax.swing.JFrame {

    /**
     * Creates new form FrameGestordeCursos
     */
    public FrameGestordeCursos(List<Curso> lista) {
        initComponents();
        this.ListaCurso = lista;
        llenarList();
        this.setLocationRelativeTo(null);
    }
    public static List<Curso> ListaCurso= new ArrayList<Curso>();    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void llenarList(){
        DefaultListModel modelo =new DefaultListModel();        
        ListaCursos.setModel(modelo); 
        modelo.removeAllElements();
        for (int i = 0; i < ListaCurso.size(); i++) {
            modelo.addElement(ListaCurso.get(i).getCodigo()+"         "+
            ListaCurso.get(i).getNombre()+"          "
            +ListaCurso.get(i).getCredito());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnEstudiante = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JLabel();
        BtnProfesor = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        lbltBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        JpanelLista = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lista = new javax.swing.JScrollPane();
        ListaCursos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("Gestor de Cursos");

        BtnEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        BtnEstudiante.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnEstudiante.setForeground(new java.awt.Color(23, 194, 154));
        BtnEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEstudiantes.png"))); // NOI18N
        BtnEstudiante.setText("Estudiantes");
        BtnEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEstudianteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEstudianteMouseExited(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(170, 26, 26));
        BtnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEliminar.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });

        BtnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnBuscar.setForeground(new java.awt.Color(20, 74, 105));
        BtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBuscar.png"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseExited(evt);
            }
        });

        BtnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(26, 158, 22));
        BtnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgregar.png"))); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseExited(evt);
            }
        });

        BtnProfesor.setBackground(new java.awt.Color(255, 255, 255));
        BtnProfesor.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        BtnProfesor.setForeground(new java.awt.Color(23, 194, 154));
        BtnProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnProfesores.png"))); // NOI18N
        BtnProfesor.setText("Profesores");
        BtnProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnProfesorMouseExited(evt);
            }
        });

        jPanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtboxBuscar.png"))); // NOI18N
        jPanelBuscar.add(lbltBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        txtBuscar.setBorder(null);
        jPanelBuscar.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 260, 30));

        JpanelLista.setBackground(new java.awt.Color(255, 255, 255));
        JpanelLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ListEstudiantes.png"))); // NOI18N
        JpanelLista.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        lista.setBorder(null);

        ListaCursos.setBorder(null);
        ListaCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setViewportView(ListaCursos);

        JpanelLista.add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 410, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JpanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnProfesor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEstudiante)
                                .addGap(40, 40, 40)
                                .addComponent(BtnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnEliminar))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnBuscar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JpanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnProfesor)
                    .addComponent(BtnAgregar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnEstudiante))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        FrameEditarCurso pantallaEditC =new FrameEditarCurso(ListaCurso);
        pantallaEditC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseEntered
     BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgregarcambio.png")));
     BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnAgregarMouseEntered

    private void BtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseExited
     BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgregar.png")));
     BtnAgregar.setForeground(new java.awt.Color(26, 158, 22));
    }//GEN-LAST:event_BtnAgregarMouseExited
    private static Curso curso = null;
    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
      String nombrCurso = txtBuscar.getText();
        boolean eliminado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    ListaCurso.remove(i);
                    eliminado= true;
                    llenarList();
                    JOptionPane.showMessageDialog(null, "Curso Eliminado",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(eliminado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Eliminar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
     BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEliminarcambio.png")));
     BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
     BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEliminar.png")));
     BtnEliminar.setForeground(new java.awt.Color(170, 26, 26));
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseClicked
       String nombrCurso = txtBuscar.getText();
        boolean encontrado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    encontrado= true;
                    llenarList();
                    this.curso=ListaCurso.get(i);
                    JOptionPane.showMessageDialog(null, "Curso Encontrado \n"
                        + "Codigo: "+ListaCurso.get(i).getCodigo()+"\n"
                        + "Nombre: "+ListaCurso.get(i).getNombre()+"\n"
                        + "Creditos: "+ListaCurso.get(i).getCredito(),
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(encontrado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Buscar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Buscar", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_BtnBuscarMouseClicked

    private void BtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseEntered
     BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBuscarcambio.png")));
     BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnBuscarMouseEntered

    private void BtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseExited
     BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBuscar.png"))); 
     BtnBuscar.setForeground(new java.awt.Color(20, 74, 105));       
    }//GEN-LAST:event_BtnBuscarMouseExited

    private void BtnProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProfesorMouseClicked
        if(this.curso!=null)
        {
            FrameProfesores pantallaP = new FrameProfesores(this.curso);
            pantallaP.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_BtnProfesorMouseClicked

    private void BtnProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProfesorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProfesorMouseEntered

    private void BtnProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProfesorMouseExited
        
    }//GEN-LAST:event_BtnProfesorMouseExited

    private void BtnEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEstudianteMouseClicked
         if(this.curso!=null)
        {
            FrameEstudiantes pantallaE = new FrameEstudiantes(this.curso);
            pantallaE.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_BtnEstudianteMouseClicked

    private void BtnEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEstudianteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEstudianteMouseEntered

    private void BtnEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEstudianteMouseExited
       
    }//GEN-LAST:event_BtnEstudianteMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestordeCursos(ListaCurso).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAgregar;
    private javax.swing.JLabel BtnBuscar;
    private javax.swing.JLabel BtnEliminar;
    private javax.swing.JLabel BtnEstudiante;
    private javax.swing.JLabel BtnProfesor;
    private javax.swing.JPanel JpanelLista;
    private javax.swing.JList<String> ListaCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JLabel lbltBuscar;
    private javax.swing.JScrollPane lista;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
